### ISSUE TITLE
NavBar should be sticky

### ISSUE THREAD

**Issue by annuk123** [Bashamega/TrendTrack#90] opened 2024-10-14 19:34 UTC
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I think, Sticky navbar looks more attractive

### Proposed Solution

So, I want to make navbar as sticky

### Do you want to work on this issue?

Yes

**Comment by Bashamega** [comment] 2024-10-15 02:52
This is a duplicate of #81

**Closed** 2024-10-15 03:20 UTC
Labels: duplicate, enhancement, status: awaiting triage

**Comment by annuk123** [comment] 2024-10-15 04:57
> This is a duplicate of #81

Sorry I didn't saw
